config:
  lobby:
    ##Habilitar el uso del comando
    enable: true
    ##Player command
    command: "vlobby"
    permission: "vlobby.use"
    message:
      sucess: ""
      denied: "&cNo tienes permisos para usar esto."